### ISSUE TITLE
Assembly annotation not working on CFGENode

### ISSUE THREAD

**Issue by wizche** [axt/bingraphvis#10]
When performing CFGEmulated analysis the returning nodes type is [CFGENode](http://angr.io/api-doc/angr.html#angr.analyses.cfg.cfg_node.CFGENode) so when its checked in the annotators logic with `type(node).__name__`, e.g. at:
https://github.com/axt/bingraphvis/blob/eb96191691635a597a7a577604cdf2cc6012c64b/bingraphvis/angr/content.py#L215
it won't match the `CFGENode` type. 
The best way to fix this is to check the for the base class matching CFGNode: `isinstance(node, angr.analyses.cfg.cfg_node.CFGNode)` instead of the current string comparisons.

**Comment by axt** [comment]
Hi! Thanks for reporting!

It was `instanceof` in the beginning, but then `angr` moved the `CFGAnalysis` into another package, and I found this way to be compatible with both versions. I think thats no longer required so we could switch it back to `instanceof` checks. 

Sorry, but I have only a very-very limited amount of time for this at the moment, so I've only added  `CFGENode` to that string based checks, which solves the problem at least temporarily, but I will keep this issue open, for a bit later, till I will have more time to solve it correctly.

PS: If you have the time/feel the power, I'm happy to accept PRs :-).
